[supabase]
host = "aws-1-ap-south-1.pooler.supabase.com"
database = "postgres"
user = "postgres.qxgxodpethnqmwheyepq"
password = "Vaishnani@2728"
port = 6543

[gemini]
api_key = "AIzaSyDosw0WiLfgTUeU8B890NQI7gUblugiHL8"