[supabase]
host = "aws-1-ap-south-1.pooler.supabase.com"
database = "postgres"
user = "postgres.qxgxodpethnqmwheyepq"
password = "Vaishnani@2728"
port = 6543

[groq]
api_key = "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"